### PR TITLE
Remove Direct DB Access, Add Nonce, Check Ajax Success

### PR DESCRIPTION
**Pull request by machouinard**
Hey, Bobby.

I wanted to push a new branch with these changes for you to peruse but was unable, so I forked instead.

Mark

### CODE REVIEW

**Comment by mrbobbybryant** [comment]
Dude. You rock!

**Comment by mrbobbybryant** [comment]
Dude, you rock!

**Comment by machouinard** [comment]
You up?

**Comment by machouinard** [comment]
Sounds like Rachel didn't leave voluntarily.  What happened there?

**Pull request merged**
